---
- name: OS - Start installimage
  ansible.builtin.shell: '/root/.oldroot/nfs/install/installimage -a -c /tmp/setup.conf -u yes -x /tmp/post_install.sh'
  notify: Restart vmhost

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
  tags: dbg_skip

- name: OS - Pause for 15 seconds
  ansible.builtin.pause:
    seconds: 15
  tags: dbg_skip

- name: OS - Update Installimage status
  ansible.builtin.file:
    path: /etc/hetzner_pve_run
    state: touch
    mode: u=rw,g=r,o=r
  tags: dbg_skip
  
# If provided, set the user’s password to the provided encrypted hash (Linux) or plain text password (macOS).
- name: compute passwd - Linux
  set_fact:
    root_password: {{ hetzner_pve_root_pass | password_hash('sha512') }}
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: compute passwd - MacOS
  set_fact:
    root_password: {{ hetzner_pve_root_pass }}
  when: ansible_distribution == 'MacOSX'

- name: OS - Update root user password
  ansible.builtin.user:
    name: "root"
    state: present
    update_password: always
    password: "{{ root_password }}"
  no_log: true
  tags: dbg_skip
