---
- name: OS - Start installimage
  ansible.builtin.shell: '/root/.oldroot/nfs/install/installimage -a -c /tmp/setup.conf -u yes -x /tmp/post_install.sh'
  notify: Restart vmhost

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
  tags: dbg_skip

- name: OS - Pause for 15 seconds
  ansible.builtin.pause:
    seconds: 15
  tags: dbg_skip

- name: OS - Update Installimage status
  ansible.builtin.file:
    path: /etc/hetzner_pve_run
    state: touch
    mode: u=rw,g=r,o=r
  tags: dbg_skip

- name: Gather ansible facts for localhost
  ansible.builtin.setup:
  delegate_to: localhost

# If provided, set the user’s password to the provided encrypted hash (Linux) or plain text password (macOS).
- name: compute passwd - Linux
  set_fact:
    root_password: "{{ hetzner_pve_root_pass | password_hash('sha512') }}"
  when: ansible_os_family == 'Debian'
  delegate_to: localhost

- name: compute passwd - MacOS
  set_fact:
    root_password: "{{ hetzner_pve_root_pass }}"
  when: ansible_os_family == 'Darwin'
  delegate_to: localhost

- name: OS - Update root user password
  ansible.builtin.user:
    name: "root"
    state: present
    update_password: always
    password: "{{ root_password }}"
  no_log: true
  tags: dbg_skip

- name: Disable "externally-managed-environment" 
  ansible.builtin.file:
    path: /usr/lib/python3.{{ ansible_python.version.minor }}/EXTERNALLY-MANAGED
    state: absent
