- name: Disable "externally-managed-environment" 
  ansible.builtin.file:
    path: /usr/lib/python3.{{ ansible_python.version.minor }}/EXTERNALLY-MANAGED
    state: absent
  delegate_to: localhost
  when: ansible_os_family != 'Darwin'
